<#
.SYNOPSIS
    Regenerates Images.lua from the .tga/.blp files found in the images folder.

.DESCRIPTION
    World of Warcraft addons run in a sandbox and cannot list a folder's contents at
    runtime, so ReforgedBreakTimer can't "see" new pictures on its own. This script is the
    practical substitute: it scans ReforgedBreakTimer\images and rewrites Images.lua to match.

    Workflow:
      1. Drop .tga or .blp files into ReforgedBreakTimer\images. (Got PNG/JPG/etc. instead? Drop
         those into ReforgedBreakTimer\images-src and run ConvertImages.ps1 instead -- it converts
         them and calls this script for you.)
      2. Run this script (double-click it, or `./GenerateImages.ps1` in a terminal).
      3. In-game, type /reload (or fully relaunch WoW).
      4. Open the options panel (gear icon on the frame) to enable/disable individual images.

.EXAMPLE
    ./GenerateImages.ps1
#>

$ErrorActionPreference = 'Stop'

$scriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$imagesDir  = Join-Path $scriptRoot 'images'
$outputFile = Join-Path $scriptRoot 'Images.lua'
$addonPath  = 'Interface\AddOns\ReforgedBreakTimer\images\'

if (-not (Test-Path $imagesDir)) {
    throw "Images folder not found: $imagesDir"
}

$files = Get-ChildItem -Path $imagesDir -File |
    Where-Object { $_.Extension -in '.tga', '.blp' } |
    Sort-Object Name

function Get-DisplayName {
    param([string]$FileBaseName)

    $spaced = ($FileBaseName -replace '[_\-]+', ' ').Trim()
    if ([string]::IsNullOrWhiteSpace($spaced)) {
        return $FileBaseName
    }
    $textInfo = (Get-Culture).TextInfo
    return $textInfo.ToTitleCase($spaced.ToLower())
}

function Escape-LuaString {
    param([string]$Value)
    return $Value.Replace('\', '\\').Replace('"', '\"')
}

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add('local _, ns = ...')
$lines.Add('')
$lines.Add('-- Auto-generated by GenerateImages.ps1 -- do not edit by hand.')
$lines.Add('-- Drop .tga or .blp files into ReforgedBreakTimer\images, run GenerateImages.ps1,')
$lines.Add('-- then /reload (or relaunch WoW) to pick up the changes.')
$lines.Add('ns.images = {')

foreach ($file in $files) {
    $base = [System.IO.Path]::GetFileNameWithoutExtension($file.Name)
    $displayName = Get-DisplayName -FileBaseName $base
    $path = "$addonPath$base"
    $luaPath = Escape-LuaString $path
    $luaName = Escape-LuaString $displayName
    $lines.Add("    { path = ""$luaPath"", name = ""$luaName"" },")
}

$lines.Add('}')


# WoW's Lua interpreter (and luac) chokes on a UTF-8 byte-order mark, so write
# plain UTF-8 without one -- Set-Content -Encoding UTF8 on Windows PowerShell
# always prepends a BOM, which is why this uses .NET's writer directly.
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllLines($outputFile, $lines, $utf8NoBom)

if ($files.Count -eq 0) {
    Write-Host "No .tga or .blp files found in $imagesDir" -ForegroundColor Yellow
    Write-Host "Images.lua was written with an empty list." -ForegroundColor Yellow
} else {
    Write-Host "Wrote $($files.Count) image(s) to Images.lua:" -ForegroundColor Green
    foreach ($file in $files) {
        Write-Host "  - $($file.Name)"
    }
    Write-Host "Now /reload in-game (or relaunch WoW) to pick up the changes." -ForegroundColor Cyan
}
