<#
.SYNOPSIS
    Regenerates Images.lua from the .tga/.blp files (and animated-GIF frame folders)
    found in the images folder.

.DESCRIPTION
    World of Warcraft addons run in a sandbox and cannot list a folder's contents at
    runtime, so ReforgedBreakTimer can't "see" new pictures on its own. This script is the
    practical substitute: it scans ReforgedBreakTimer\images and rewrites Images.lua to match.

    Two kinds of entries come out of that scan:
      - A .tga/.blp file directly in images\ becomes a plain static picture entry.
      - A subfolder of images\ (as ConvertImages.ps1 produces for an animated GIF -- e.g.
        images\wave\0001.tga, 0002.tga, ... plus a delay.txt) becomes an animated entry:
        an ordered list of frame paths plus the per-frame delay, which the addon cycles
        through at runtime.

    Workflow:
      1. Drop .tga or .blp files into ReforgedBreakTimer\images (or a subfolder of numbered
         frame files + delay.txt for an animation). Got PNG/JPG/GIF/etc. instead? Drop those
         into ReforgedBreakTimer\images-src and run ConvertImages.ps1 instead -- it converts
         them and calls this script for you.
      2. Run this script (double-click it, or `./GenerateImages.ps1` in a terminal).
      3. In-game, type /reload (or fully relaunch WoW).
      4. Open the options panel (Game Menu (Esc) -> Options -> AddOns -> Reforged
         Break Timer) to enable/disable individual images.

.EXAMPLE
    ./GenerateImages.ps1
#>

$ErrorActionPreference = 'Stop'

$scriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$imagesDir  = Join-Path $scriptRoot 'images'
$outputFile = Join-Path $scriptRoot 'Images.lua'
$addonPath  = 'Interface\AddOns\ReforgedBreakTimer\images\'

if (-not (Test-Path $imagesDir)) {
    throw "Images folder not found: $imagesDir"
}

# Static pictures: .tga/.blp files directly in images\.
$staticFiles = Get-ChildItem -Path $imagesDir -File |
    Where-Object { $_.Extension -in '.tga', '.blp' } |
    Sort-Object Name

# Animated pictures: subfolders of images\, each holding numbered frame files.
$animatedDirs = Get-ChildItem -Path $imagesDir -Directory | Sort-Object Name

function Get-DisplayName {
    param([string]$FileBaseName)

    $spaced = ($FileBaseName -replace '[_\-]+', ' ').Trim()
    if ([string]::IsNullOrWhiteSpace($spaced)) {
        return $FileBaseName
    }
    $textInfo = (Get-Culture).TextInfo
    return $textInfo.ToTitleCase($spaced.ToLower())
}

function Escape-LuaString {
    param([string]$Value)
    return $Value.Replace('\', '\\').Replace('"', '\"')
}

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add('local _, ns = ...')
$lines.Add('')
$lines.Add('-- Auto-generated by GenerateImages.ps1 -- do not edit by hand.')
$lines.Add('-- Drop .tga/.blp files (or animated-GIF frame subfolders) into')
$lines.Add('-- ReforgedBreakTimer\images, run GenerateImages.ps1, then /reload (or')
$lines.Add('-- relaunch WoW) to pick up the changes.')
$lines.Add('ns.images = {')

$entryCount = 0
$emittedAnimatedDirs = New-Object System.Collections.Generic.List[object]

foreach ($file in $staticFiles) {
    $base = [System.IO.Path]::GetFileNameWithoutExtension($file.Name)
    $displayName = Get-DisplayName -FileBaseName $base
    $path = "$addonPath$base"
    $luaPath = Escape-LuaString $path
    $luaName = Escape-LuaString $displayName
    $lines.Add("    { path = ""$luaPath"", name = ""$luaName"" },")
    $entryCount++
}

foreach ($dir in $animatedDirs) {
    $frameFiles = Get-ChildItem -Path $dir.FullName -File |
        Where-Object { $_.Extension -in '.tga', '.blp' } |
        Sort-Object Name

    if ($frameFiles.Count -eq 0) {
        Write-Warning "Skipping $($dir.Name)\ -- no .tga/.blp frame files in it."
        continue
    }

    $delayFile = Join-Path $dir.FullName 'delay.txt'
    $delaySeconds = 0.1
    if (Test-Path -LiteralPath $delayFile -PathType Leaf) {
        $delayText = (Get-Content -LiteralPath $delayFile -Raw).Trim()
        $parsed = 0.0
        if ([double]::TryParse($delayText, [System.Globalization.NumberStyles]::Float, [System.Globalization.CultureInfo]::InvariantCulture, [ref]$parsed) -and $parsed -gt 0) {
            $delaySeconds = $parsed
        } else {
            Write-Warning "$($dir.Name)\delay.txt is missing or unreadable; defaulting to ${delaySeconds}s per frame."
        }
    } else {
        Write-Warning "$($dir.Name)\ has no delay.txt; defaulting to ${delaySeconds}s per frame."
    }
    $luaDelay = $delaySeconds.ToString([System.Globalization.CultureInfo]::InvariantCulture)

    $displayName = Get-DisplayName -FileBaseName $dir.Name
    $firstFramePath = "$addonPath$($dir.Name)\$([System.IO.Path]::GetFileNameWithoutExtension($frameFiles[0].Name))"
    $luaPath = Escape-LuaString $firstFramePath
    $luaName = Escape-LuaString $displayName

    $lines.Add("    { path = ""$luaPath"", name = ""$luaName"", delay = $luaDelay, frames = {")
    foreach ($frameFile in $frameFiles) {
        $frameBase = [System.IO.Path]::GetFileNameWithoutExtension($frameFile.Name)
        $framePath = "$addonPath$($dir.Name)\$frameBase"
        $luaFramePath = Escape-LuaString $framePath
        $lines.Add("        ""$luaFramePath"",")
    }
    $lines.Add("    } },")
    $entryCount++
    $emittedAnimatedDirs.Add($dir)
}

$lines.Add('}')


# WoW's Lua interpreter (and luac) chokes on a UTF-8 byte-order mark, so write
# plain UTF-8 without one -- Set-Content -Encoding UTF8 on Windows PowerShell
# always prepends a BOM, which is why this uses .NET's writer directly.
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllLines($outputFile, $lines, $utf8NoBom)

if ($entryCount -eq 0) {
    Write-Host "No .tga/.blp files or animated-GIF folders found in $imagesDir" -ForegroundColor Yellow
    Write-Host "Images.lua was written with an empty list." -ForegroundColor Yellow
} else {
    Write-Host "Wrote $entryCount image(s) to Images.lua:" -ForegroundColor Green
    foreach ($file in $staticFiles) {
        Write-Host "  - $($file.Name)"
    }
    foreach ($dir in $emittedAnimatedDirs) {
        Write-Host "  - $($dir.Name)\ (animated)"
    }
    Write-Host "Now /reload in-game (or relaunch WoW) to pick up the changes." -ForegroundColor Cyan
}
