local _, ns = ...

-- Auto-generated by GenerateImages.ps1 -- do not edit by hand.
-- Drop .tga/.blp files (or animated-GIF sprite-sheet subfolders) into
-- ReforgedBreakTimer\images, run GenerateImages.ps1, then /reload (or
-- relaunch WoW) to pick up the changes.
ns.images = {
    { path = "Interface\\AddOns\\ReforgedBreakTimer\\images\\blackguy", name = "Blackguy" },
    { path = "Interface\\AddOns\\ReforgedBreakTimer\\images\\catcat", name = "Catcat" },
    { path = "Interface\\AddOns\\ReforgedBreakTimer\\images\\devcat", name = "Devcat" },
    { path = "Interface\\AddOns\\ReforgedBreakTimer\\images\\diazcat", name = "Diazcat" },
    { path = "Interface\\AddOns\\ReforgedBreakTimer\\images\\eveecats", name = "Eveecats" },
    { path = "Interface\\AddOns\\ReforgedBreakTimer\\images\\grom", name = "Grom" },
    { path = "Interface\\AddOns\\ReforgedBreakTimer\\images\\hydrohat", name = "Hydrohat" },
    { path = "Interface\\AddOns\\ReforgedBreakTimer\\images\\iondiaz", name = "Iondiaz" },
    { path = "Interface\\AddOns\\ReforgedBreakTimer\\images\\lescat", name = "Lescat" },
    { path = "Interface\\AddOns\\ReforgedBreakTimer\\images\\lindsaycat", name = "Lindsaycat" },
    { path = "Interface\\AddOns\\ReforgedBreakTimer\\images\\loyalaydox", name = "Loyalaydox" },
    { path = "Interface\\AddOns\\ReforgedBreakTimer\\images\\macrohat", name = "Macrohat" },
    { path = "Interface\\AddOns\\ReforgedBreakTimer\\images\\pogwilkz", name = "Pogwilkz" },
    { path = "Interface\\AddOns\\ReforgedBreakTimer\\images\\quazi", name = "Quazi" },
    { path = "Interface\\AddOns\\ReforgedBreakTimer\\images\\rivenz", name = "Rivenz" },
    { path = "Interface\\AddOns\\ReforgedBreakTimer\\images\\smashcat", name = "Smashcat" },
    { path = "Interface\\AddOns\\ReforgedBreakTimer\\images\\sneascat", name = "Sneascat" },
    { path = "Interface\\AddOns\\ReforgedBreakTimer\\images\\valcats", name = "Valcats" },
    { path = "Interface\\AddOns\\ReforgedBreakTimer\\images\\yipzhat", name = "Yipzhat" },
    { path = "Interface\\AddOns\\ReforgedBreakTimer\\images\\cat-standing\\sheet", name = "Cat Standing", delay = 0.1, frames = 60, columns = 8, rows = 8, frameWidth = 100, frameHeight = 178 },
    { path = "Interface\\AddOns\\ReforgedBreakTimer\\images\\hump-day-happy-meeting\\sheet", name = "Hump Day Happy Meeting", delay = 0.0835593220338983, frames = 59, columns = 8, rows = 8, frameWidth = 134, frameHeight = 178 },
    { path = "Interface\\AddOns\\ReforgedBreakTimer\\images\\pedro\\sheet", name = "Pedro", delay = 0.110169491525424, frames = 59, columns = 8, rows = 8, frameWidth = 141, frameHeight = 178 },
    { path = "Interface\\AddOns\\ReforgedBreakTimer\\images\\the-voices-meme\\sheet", name = "The Voices Meme", delay = 0.143965517241379, frames = 58, columns = 8, rows = 8, frameWidth = 178, frameHeight = 154 },
}
