local _, ns = ...

-- Auto-generated by GenerateImages.ps1 -- do not edit by hand.
-- Drop .tga or .blp files into ReforgedBreakTimer\images, run GenerateImages.ps1,
-- then /reload (or relaunch WoW) to pick up the changes.
ns.images = {
    { path = "Interface\\AddOns\\ReforgedBreakTimer\\images\\blackguy", name = "Blackguy" },
    { path = "Interface\\AddOns\\ReforgedBreakTimer\\images\\grom", name = "Grom" },
    { path = "Interface\\AddOns\\ReforgedBreakTimer\\images\\hydrohat", name = "Hydrohat" },
    { path = "Interface\\AddOns\\ReforgedBreakTimer\\images\\iondiaz", name = "Iondiaz" },
    { path = "Interface\\AddOns\\ReforgedBreakTimer\\images\\macrohat", name = "Macrohat" },
    { path = "Interface\\AddOns\\ReforgedBreakTimer\\images\\pogwilkz", name = "Pogwilkz" },
    { path = "Interface\\AddOns\\ReforgedBreakTimer\\images\\quazi", name = "Quazi" },
    { path = "Interface\\AddOns\\ReforgedBreakTimer\\images\\rivenz", name = "Rivenz" },
    { path = "Interface\\AddOns\\ReforgedBreakTimer\\images\\yipzhat", name = "Yipzhat" },
}
